workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - flutter create .
      - flutter pub get
      - flutter build ios --release

    artifacts:
      - build/ios/iphoneos/*.app
